### ISSUE TITLE
npm publish

### ISSUE THREAD

**Issue by Flet** [atom/atom-dark-syntax#18]
Is it possible to publish this package to npm? As a user of `highlights`, it would be nice to depend on this in `package.json` via an npm package instead of via git+https.

**Comment by simurai** [comment]
> As a user of highlights

Do you mean using this theme together with [highlight.js](https://highlightjs.org/)? I think that's not really possible since the scope selectors are different. Atom themes are mostly based on TextMate's. And they also include other styling like for the gutter that wouldn't be needed outside of Atom.

But feel free to fork this theme and then port it to be used with `highlight.js`.

**Comment by Flet** [comment]
Nope, I mean https://github.com/atom/highlights (by way of https://github.com/npm/marky-markdown) :smile:
