### ISSUE TITLE
I wish a white color

### ISSUE THREAD

**Issue by LionWY** [atom/atom-dark-syntax#33]
it's now the theme
![qq20161130-1](https://cloud.githubusercontent.com/assets/5524753/20736634/b2771bc0-b6e2-11e6-84bd-47744f781d27.png)

I wish this them
![qq20161130-2](https://cloud.githubusercontent.com/assets/5524753/20736650/cf3ec384-b6e2-11e6-9994-f9a31cec1847.png)

how to change it? can you help me ?

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
