### ISSUE TITLE
Show different color on html tag name and tag attributes

### ISSUE THREAD

**Issue by yubaoquan** [atom/atom-dark-syntax#44]
Now in html file, the colors of tag name and tag attributes are the same, I suggest to make them different so that the code looks more beautiful.

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
